    Write-Output "# Always Run As Administrator"
    Write-Output "# Always Run Tool From C:\ Drive"
    Write-Output "# Compatible With: Falcon Crowdstrike and Palo Alto Cortex XDR."
    Write-Output ""
    Write-Output "┌> How To Run Example: ForensicMiner.ps1 -O ZIP"
    Write-Output "├~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~╮"
    Write-Output "│                               Options (-O)                               │"
    Write-Output "├~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~┤"
    Write-Output "│                                                                          │"
    Write-Output "│1. ZIP          ZIP Evidence You gathered From Forensic Miner Tool        │"
    Write-Output "│                                                                          │"
    Write-Output "│2. Menu         Show Menu Of What You Can Do With Forensic Miner Tool     │"
    Write-Output "│                                                                          │"
    Write-Output "│3. Purge        Purge Forensic Miner Tool Footprint From This Host        │"
    Write-Output "│                                                                          │"
    Write-Output "│4. Update       Update Forensic Miner to the latest version               │"
    Write-Output "│                                                                          │"
    Write-Output "╰~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~╯"
    Write-Output ""
    Write-Output "┌> How To Run Example: ForensicMiner.ps1 -A RunMRU"
    Write-Output "├~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~╮"
    Write-Output "│                               Analyze  (-A)                              │"
    Write-Output "├~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~┤"
    Write-Output "│                                                                          │"
    Write-Output '│0. Harvest      Harvest all "Analyze" table features                      │'
    Write-Output "│                                                                          │"
    Write-Output "│1. BAM          Get all users evidence of executions using BAM.sys        │"
    Write-Output "│                                                                          │"
    Write-Output "│2. RunMRU       Get record all users history of Run.exe                   │"
    Write-Output "│                                                                          │"
    Write-Output "│3. MUICache     Get record of Applications\Tools Installed\Run by users   │"
    Write-Output "│                                                                          │"
    Write-Output "│4. RecentDocs   Get processed and fillterd RecentDocs artifact all users  │"
    Write-Output "│                                                                          │"
    Write-Output "│5. RecentItems  Get list of all the users RecentItems folder              │"
    Write-Output "│                                                                          │"
    Write-Output "│6. WiFiHistory  Get information record of Wi-Fi History\Activity\Settings │"
    Write-Output "│                                                                          │"
    Write-Output "│7. BrowserAnalyzer Get analyzed information on all users browsers         │"
    Write-Output "│                                                                          │"
    Write-Output "│8. TypedPaths   Get record of Explorer.exe TypedPaths                     │"
    Write-Output "│                                                                          │"
    Write-Output "╰~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~╯"
    Write-Output ""
    Write-Output "┌> How To Run Example: ForensicMiner.ps1 -C BrowserHistory"
    Write-Output "├~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~╮"
    Write-Output "│                          Collect Artifacts (-C)                          │"
    Write-Output "├~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~┤"
    Write-Output "│                                                                          │"
    Write-Output "│1. SystemEvents    Collect All Windows System Events From This Host       │"
    Write-Output "│                                                                          │"
    Write-Output "│2. BrowserHistory  Collect History Files From All Installed Browsers      │"
    Write-Output "│                                                                          │"
    Write-Output "╰~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~╯"
    Write-Output ""
