    Write-Output "# Always Run As Administrator"
    Write-Output "# Always Run Tool From C:\ Drive"
    Write-Output "# Compatible With: Falcon Crowdstrike and Palo Alto Cortex XDR."
    Write-Output ""
    Write-Output "┌> How To Run Example: ForensicMiner.ps1 -O ZIP"
    Write-Output "├~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~╮"
    Write-Output "│                               Options (-O)                               │"
    Write-Output "├~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~┤"
    Write-Output "│                                                                          │"
    Write-Output "│1. ZIP          ZIP Evidence You gathered From Forensic Miner Tool        │"
    Write-Output "│                                                                          │"
    Write-Output "│2. Menu         Show Menu Of What You Can Do With Forensic Miner Tool     │"
    Write-Output "│                                                                          │"
    Write-Output "│3. Purge        Purge Forensic Miner Tool Footprint From This Host        │"
    Write-Output "│                                                                          │"
    Write-Output "╰~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~╯"
    Write-Output ""
    Write-Output "┌> How To Run Example: ForensicMiner.ps1 -A RunMRU"
    Write-Output "├~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~╮"
    Write-Output "│                               Analyze  (-A)                              │"
    Write-Output "├~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~┤"
    Write-Output "│                                                                          │"
    Write-Output '│0. Harvest      Harvest All "Analyze" Table features                      │'
    Write-Output "│                                                                          │"
    Write-Output "│1. BAM          Get All Users Evidence of Executions Using BAM.sys        │"
    Write-Output "│                                                                          │"
    Write-Output "│2. RunMRU       Get Record All Users History Of Run.exe                   │"
    Write-Output "│                                                                          │"
    Write-Output "│3. MUICache     Get Record Of Applications\Tools Installed\Run By Users   │"
    Write-Output "│                                                                          │"
    Write-Output "│4. RecentDocs   Get Processed and Fillterd RecentDocs Artifact All Users  │"
    Write-Output "│                                                                          │"
    Write-Output "│5. RecentItems  Get List Of All The Users RecentItems Folder              │"
    Write-Output "│                                                                          │"
    Write-Output "│6. WiFiHistory  Get Information Record Of Wi-Fi History\Activity\Settings │"
    Write-Output "│                                                                          │"
    Write-Output "│7. BrowserAnalyzer Get Analyzed Information On All Users Browsers         │"
    Write-Output "│                                                                          │"
    Write-Output "╰~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~╯"
    Write-Output ""
    Write-Output "┌> How To Run Example: ForensicMiner.ps1 -C BrowserHistory"
    Write-Output "├~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~╮"
    Write-Output "│                          Collect Artifacts (-C)                          │"
    Write-Output "├~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~┤"
    Write-Output "│                                                                          │"
    Write-Output "│1. SystemEvents    Collect All Windows System Events From This Host       │"
    Write-Output "│                                                                          │"
    Write-Output "│2. BrowserHistory  Collect History Files From All Installed Browsers      │"
    Write-Output "│                                                                          │"
    Write-Output "╰~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~╯"
    Write-Output ""